# docker-compose.yml

version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=nest_blog